/* The following code was generated by JFlex 1.6.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>/home/jorge/Documentos/Compiladores/proyecto/compilador/src/Lexer.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\5\1\3\1\2\1\12\1\13\1\1\16\5\4\0\1\46\1\0"+
    "\1\50\1\0\1\4\1\27\2\0\1\51\1\15\1\11\1\27\1\0"+
    "\1\27\1\0\1\10\1\6\11\7\1\0\1\47\1\30\1\31\1\30"+
    "\2\0\32\4\1\0\1\53\2\0\1\4\1\0\1\22\1\44\1\43"+
    "\1\21\1\17\1\24\1\34\1\45\1\36\2\4\1\25\1\35\1\37"+
    "\1\23\1\33\1\4\1\20\1\26\1\40\1\52\1\16\2\4\1\32"+
    "\1\4\1\41\1\0\1\42\1\0\6\5\1\14\32\5\2\0\4\4"+
    "\4\0\1\4\2\0\1\5\7\0\1\4\4\0\1\4\5\0\27\4"+
    "\1\0\37\4\1\0\u01ca\4\4\0\14\4\16\0\5\4\7\0\1\4"+
    "\1\0\1\4\21\0\160\5\5\4\1\0\2\4\2\0\4\4\10\0"+
    "\1\4\1\0\3\4\1\0\1\4\1\0\24\4\1\0\123\4\1\0"+
    "\213\4\1\0\5\5\2\0\236\4\11\0\46\4\2\0\1\4\7\0"+
    "\47\4\11\0\55\5\1\0\1\5\1\0\2\5\1\0\2\5\1\0"+
    "\1\5\10\0\33\4\5\0\3\4\15\0\4\5\7\0\1\4\4\0"+
    "\13\5\5\0\53\4\37\5\4\0\2\4\1\5\143\4\1\0\1\4"+
    "\10\5\1\0\6\5\2\4\2\5\1\0\4\5\2\4\12\5\3\4"+
    "\2\0\1\4\17\0\1\5\1\4\1\5\36\4\33\5\2\0\131\4"+
    "\13\5\1\4\16\0\12\5\41\4\11\5\2\4\4\0\1\4\5\0"+
    "\26\4\4\5\1\4\11\5\1\4\3\5\1\4\5\5\22\0\31\4"+
    "\3\5\244\0\4\5\66\4\3\5\1\4\22\5\1\4\7\5\12\4"+
    "\2\5\2\0\12\5\1\0\7\4\1\0\7\4\1\0\3\5\1\0"+
    "\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0\1\4\3\0"+
    "\4\4\2\0\1\5\1\4\7\5\2\0\2\5\2\0\3\5\1\4"+
    "\10\0\1\5\4\0\2\4\1\0\3\4\2\5\2\0\12\5\4\4"+
    "\7\0\1\4\5\0\3\5\1\0\6\4\4\0\2\4\2\0\26\4"+
    "\1\0\7\4\1\0\2\4\1\0\2\4\1\0\2\4\2\0\1\5"+
    "\1\0\5\5\4\0\2\5\2\0\3\5\3\0\1\5\7\0\4\4"+
    "\1\0\1\4\7\0\14\5\3\4\1\5\13\0\3\5\1\0\11\4"+
    "\1\0\3\4\1\0\26\4\1\0\7\4\1\0\2\4\1\0\5\4"+
    "\2\0\1\5\1\4\10\5\1\0\3\5\1\0\3\5\2\0\1\4"+
    "\17\0\2\4\2\5\2\0\12\5\1\0\1\4\17\0\3\5\1\0"+
    "\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4\1\0"+
    "\5\4\2\0\1\5\1\4\7\5\2\0\2\5\2\0\3\5\10\0"+
    "\2\5\4\0\2\4\1\0\3\4\2\5\2\0\12\5\1\0\1\4"+
    "\20\0\1\5\1\4\1\0\6\4\3\0\3\4\1\0\4\4\3\0"+
    "\2\4\1\0\1\4\1\0\2\4\3\0\2\4\3\0\3\4\3\0"+
    "\14\4\4\0\5\5\3\0\3\5\1\0\4\5\2\0\1\4\6\0"+
    "\1\5\16\0\12\5\11\0\1\4\7\0\3\5\1\0\10\4\1\0"+
    "\3\4\1\0\27\4\1\0\12\4\1\0\5\4\3\0\1\4\7\5"+
    "\1\0\3\5\1\0\4\5\7\0\2\5\1\0\2\4\6\0\2\4"+
    "\2\5\2\0\12\5\22\0\2\5\1\0\10\4\1\0\3\4\1\0"+
    "\27\4\1\0\12\4\1\0\5\4\2\0\1\5\1\4\7\5\1\0"+
    "\3\5\1\0\4\5\7\0\2\5\7\0\1\4\1\0\2\4\2\5"+
    "\2\0\12\5\1\0\2\4\17\0\2\5\1\0\10\4\1\0\3\4"+
    "\1\0\51\4\2\0\1\4\7\5\1\0\3\5\1\0\4\5\1\4"+
    "\10\0\1\5\10\0\2\4\2\5\2\0\12\5\12\0\6\4\2\0"+
    "\2\5\1\0\22\4\3\0\30\4\1\0\11\4\1\0\1\4\2\0"+
    "\7\4\3\0\1\5\4\0\6\5\1\0\1\5\1\0\10\5\22\0"+
    "\2\5\15\0\60\4\1\5\2\4\7\5\4\0\10\4\10\5\1\0"+
    "\12\5\47\0\2\4\1\0\1\4\2\0\2\4\1\0\1\4\2\0"+
    "\1\4\6\0\4\4\1\0\7\4\1\0\3\4\1\0\1\4\1\0"+
    "\1\4\2\0\2\4\1\0\4\4\1\5\2\4\6\5\1\0\2\5"+
    "\1\4\2\0\5\4\1\0\1\4\1\0\6\5\2\0\12\5\2\0"+
    "\2\4\42\0\1\4\27\0\2\5\6\0\12\5\13\0\1\5\1\0"+
    "\1\5\1\0\1\5\4\0\2\5\10\4\1\0\44\4\4\0\24\5"+
    "\1\0\2\5\5\4\13\5\1\0\44\5\11\0\1\5\71\0\53\4"+
    "\24\5\1\4\12\5\6\0\6\4\4\5\4\4\3\5\1\4\3\5"+
    "\2\4\7\5\3\4\4\5\15\4\14\5\1\4\17\5\2\0\46\4"+
    "\12\0\53\4\1\0\1\4\3\0\u0149\4\1\0\4\4\2\0\7\4"+
    "\1\0\1\4\1\0\4\4\2\0\51\4\1\0\4\4\2\0\41\4"+
    "\1\0\4\4\2\0\7\4\1\0\1\4\1\0\4\4\2\0\17\4"+
    "\1\0\71\4\1\0\4\4\2\0\103\4\2\0\3\5\40\0\20\4"+
    "\20\0\125\4\14\0\u026c\4\2\0\21\4\1\0\32\4\5\0\113\4"+
    "\3\0\3\4\17\0\15\4\1\0\4\4\3\5\13\0\22\4\3\5"+
    "\13\0\22\4\2\5\14\0\15\4\1\0\3\4\1\0\2\5\14\0"+
    "\64\4\40\5\3\0\1\4\3\0\2\4\1\5\2\0\12\5\41\0"+
    "\3\5\2\0\12\5\6\0\130\4\10\0\51\4\1\5\1\4\5\0"+
    "\106\4\12\0\35\4\3\0\14\5\4\0\14\5\12\0\12\5\36\4"+
    "\2\0\5\4\13\0\54\4\4\0\21\5\7\4\2\5\6\0\12\5"+
    "\46\0\27\4\5\5\4\0\65\4\12\5\1\0\35\5\2\0\13\5"+
    "\6\0\12\5\15\0\1\4\130\0\5\5\57\4\21\5\7\4\4\0"+
    "\12\5\21\0\11\5\14\0\3\5\36\4\12\5\3\0\2\4\12\5"+
    "\6\0\46\4\16\5\14\0\44\4\24\5\10\0\12\5\3\0\3\4"+
    "\12\5\44\4\122\0\3\5\1\0\25\5\4\4\1\5\4\4\1\5"+
    "\15\0\300\4\47\5\25\0\4\5\u0116\4\2\0\6\4\2\0\46\4"+
    "\2\0\6\4\2\0\10\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\37\4\2\0\65\4\1\0\7\4\1\0\1\4\3\0\3\4"+
    "\1\0\7\4\3\0\4\4\2\0\6\4\4\0\15\4\5\0\3\4"+
    "\1\0\7\4\16\0\5\5\30\0\1\12\1\12\5\5\20\0\2\4"+
    "\23\0\1\4\13\0\5\5\5\0\6\5\1\0\1\4\15\0\1\4"+
    "\20\0\15\4\3\0\32\4\26\0\15\5\4\0\1\5\3\0\14\5"+
    "\21\0\1\4\4\0\1\4\2\0\12\4\1\0\1\4\3\0\5\4"+
    "\6\0\1\4\1\0\1\4\1\0\1\4\1\0\4\4\1\0\13\4"+
    "\2\0\4\4\5\0\5\4\4\0\1\4\21\0\51\4\u0a77\0\57\4"+
    "\1\0\57\4\1\0\205\4\6\0\4\4\3\5\16\0\46\4\12\0"+
    "\66\4\11\0\1\4\17\0\1\5\27\4\11\0\7\4\1\0\7\4"+
    "\1\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4"+
    "\1\0\7\4\1\0\40\5\57\0\1\4\u01d5\0\3\4\31\0\11\4"+
    "\6\5\1\0\5\4\2\0\5\4\4\0\126\4\2\0\2\5\2\0"+
    "\3\4\1\0\132\4\1\0\4\4\5\0\51\4\3\0\136\4\21\0"+
    "\33\4\65\0\20\4\u0200\0\u19b6\4\112\0\u51cc\4\64\0\u048d\4\103\0"+
    "\56\4\2\0\u010d\4\3\0\20\4\12\5\2\4\24\0\57\4\1\5"+
    "\14\0\2\5\1\0\31\4\10\0\120\4\2\5\45\0\11\4\2\0"+
    "\147\4\2\0\4\4\1\0\2\4\16\0\12\4\120\0\10\4\1\5"+
    "\3\4\1\5\4\4\1\5\27\4\5\5\20\0\1\4\7\0\64\4"+
    "\14\0\2\5\62\4\21\5\13\0\12\5\6\0\22\5\6\4\3\0"+
    "\1\4\4\0\12\5\34\4\10\5\2\0\27\4\15\5\14\0\35\4"+
    "\3\0\4\5\57\4\16\5\16\0\1\4\12\5\46\0\51\4\16\5"+
    "\11\0\3\4\1\5\10\4\2\5\2\0\12\5\6\0\27\4\3\0"+
    "\1\4\1\5\4\0\60\4\1\5\1\4\3\5\2\4\2\5\5\4"+
    "\2\5\1\4\1\5\1\4\30\0\3\4\43\0\6\4\2\0\6\4"+
    "\2\0\6\4\11\0\7\4\1\0\7\4\221\0\43\4\10\5\1\0"+
    "\2\5\2\0\12\5\6\0\u2ba4\4\14\0\27\4\4\0\61\4\u2104\0"+
    "\u012e\4\2\0\76\4\2\0\152\4\46\0\7\4\14\0\5\4\5\0"+
    "\1\4\1\5\12\4\1\0\15\4\1\0\5\4\1\0\1\4\1\0"+
    "\2\4\1\0\2\4\1\0\154\4\41\0\u016b\4\22\0\100\4\2\0"+
    "\66\4\50\0\15\4\3\0\20\5\20\0\7\5\14\0\2\4\30\0"+
    "\3\4\31\0\1\4\6\0\5\4\1\0\207\4\2\0\1\5\4\0"+
    "\1\4\13\0\12\5\7\0\32\4\4\0\1\4\1\0\32\4\13\0"+
    "\131\4\3\0\6\4\2\0\6\4\2\0\6\4\2\0\3\4\3\0"+
    "\2\4\3\0\2\4\22\0\3\5\4\0\14\4\1\0\32\4\1\0"+
    "\23\4\1\0\2\4\1\0\17\4\2\0\16\4\42\0\173\4\105\0"+
    "\65\4\210\0\1\5\202\0\35\4\3\0\61\4\57\0\37\4\21\0"+
    "\33\4\65\0\36\4\2\0\44\4\4\0\10\4\1\0\5\4\52\0"+
    "\236\4\2\0\12\5\u0356\0\6\4\2\0\1\4\1\0\54\4\1\0"+
    "\2\4\3\0\1\4\2\0\27\4\252\0\26\4\12\0\32\4\306\0"+
    "\1\4\3\5\1\0\2\5\5\0\4\5\4\4\1\0\3\4\1\0"+
    "\33\4\4\0\3\5\4\0\1\5\40\0\35\4\203\0\66\4\12\0"+
    "\26\4\12\0\23\4\215\0\111\4\u03b7\0\3\5\65\4\17\5\37\0"+
    "\12\5\20\0\3\5\55\4\13\5\2\0\1\5\u0f42\0\u036f\4\221\0"+
    "\143\4\u0b9d\0\u042f\4\u33d1\0\u0239\4\u45c7\0\2\4\u2163\0\5\5\3\0"+
    "\26\5\2\0\7\5\36\0\4\5\224\0\3\5\u01bb\0\125\4\1\0"+
    "\107\4\1\0\2\4\2\0\1\4\2\0\2\4\2\0\4\4\1\0"+
    "\14\4\1\0\1\4\1\0\7\4\1\0\101\4\1\0\4\4\2\0"+
    "\10\4\1\0\7\4\1\0\34\4\1\0\4\4\1\0\5\4\1\0"+
    "\1\4\3\0\7\4\1\0\u0154\4\2\0\31\4\1\0\31\4\1\0"+
    "\37\4\1\0\31\4\1\0\37\4\1\0\31\4\1\0\37\4\1\0"+
    "\31\4\1\0\37\4\1\0\31\4\1\0\10\4\2\0\62\5\u2800\0"+
    "\ua6d7\4\51\0\u1035\4\13\0\336\4\u3fe2\0\u021e\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\5\36\0\140\5\200\0\360\5\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\2\4\1\1\1\5\1\6"+
    "\3\3\1\7\3\3\1\5\1\10\1\11\3\3\1\12"+
    "\1\13\2\3\1\14\1\15\1\16\1\17\1\20\3\0"+
    "\1\2\1\0\7\3\1\21\1\10\3\3\1\22\10\3"+
    "\1\23\1\3\1\0\15\3\1\0\1\3\1\24\1\3"+
    "\1\25\6\3\1\26\1\27\1\3\1\30\3\3\1\31"+
    "\2\3\1\32\1\3\1\33\2\3\1\34\1\3\1\35"+
    "\3\3\1\36\1\37\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\130\0\260\0\130\0\334"+
    "\0\u0108\0\u0134\0\130\0\u0160\0\u018c\0\u01b8\0\260\0\u01e4"+
    "\0\u0210\0\u023c\0\130\0\u0268\0\u0268\0\u0294\0\u02c0\0\u02ec"+
    "\0\130\0\130\0\u0318\0\u0344\0\130\0\130\0\130\0\u0370"+
    "\0\130\0\u039c\0\u03c8\0\u0134\0\u0134\0\u03f4\0\u0420\0\u044c"+
    "\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u0554\0\130\0\u0580"+
    "\0\u05ac\0\u05d8\0\260\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4"+
    "\0\u06e0\0\u070c\0\u0738\0\260\0\u0764\0\u0790\0\u07bc\0\u07e8"+
    "\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948"+
    "\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\260\0\u0a50\0\260"+
    "\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\260\0\260"+
    "\0\u0b84\0\130\0\u0bb0\0\u0bdc\0\u0c08\0\260\0\u0c34\0\u0c60"+
    "\0\260\0\u0c8c\0\260\0\u0cb8\0\u0ce4\0\260\0\u0d10\0\260"+
    "\0\u0d3c\0\u0d68\0\u0d94\0\260\0\260\0\260";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\3\1\5\1\3\1\13\1\14\1\15\1\6"+
    "\1\16\1\6\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\17\1\26\1\6\1\27\1\6\1\30\1\6"+
    "\1\31\1\32\1\33\1\6\1\34\1\5\1\35\1\36"+
    "\1\37\1\6\1\3\1\40\2\3\45\40\1\41\2\40"+
    "\1\3\56\0\1\5\55\0\4\6\4\0\1\6\1\0"+
    "\11\6\3\0\7\6\2\0\3\6\4\0\1\6\7\0"+
    "\2\10\54\0\1\42\1\43\42\0\1\44\2\45\5\44"+
    "\1\0\1\46\3\44\1\0\33\44\1\0\2\44\4\0"+
    "\4\6\4\0\1\6\1\0\1\6\1\47\7\6\3\0"+
    "\7\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\10\6\1\50\3\0\5\6\1\51\1\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\1\6\1\52\7\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\4\6"+
    "\1\53\4\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\1\6\1\54\3\6"+
    "\1\55\3\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\11\6\3\0\4\6"+
    "\1\56\2\6\2\0\3\6\4\0\1\6\32\0\1\57"+
    "\26\0\4\6\4\0\1\6\1\0\2\6\1\60\1\6"+
    "\1\61\4\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\11\6\3\0\4\6"+
    "\1\62\2\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\5\6\1\63\3\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\64\5\0\4\6\4\0\1\6"+
    "\1\0\4\6\1\65\4\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\4\6"+
    "\1\66\4\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\1\0\1\40\2\0\45\40\1\0\2\40\1\0\1\42"+
    "\1\4\1\5\7\42\3\0\37\42\11\0\1\44\52\0"+
    "\1\5\47\0\4\6\4\0\1\6\1\0\2\6\1\67"+
    "\6\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\11\6\3\0\7\6\2\0"+
    "\1\70\2\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\11\6\3\0\6\6\1\71\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\10\6\1\72"+
    "\3\0\7\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\7\6\1\73\1\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\1\6\1\74\7\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\11\6"+
    "\3\0\2\6\1\75\4\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\11\6\3\0\7\6"+
    "\2\0\3\6\1\76\3\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\5\6\1\77\3\6\3\0\7\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\2\6\1\100\6\6\3\0\7\6\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\1\6\1\101"+
    "\7\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\7\6\1\102\1\6\3\0"+
    "\7\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\3\6\1\103\5\6\3\0\7\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\10\6\1\104\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\3\6\1\105\5\6"+
    "\3\0\7\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\2\6\1\106\6\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\1\6\1\107\3\6\1\110\3\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\3\6\1\111\5\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\10\6"+
    "\1\112\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\11\6\3\0\4\6\1\113"+
    "\2\6\2\0\3\6\4\0\1\6\40\0\1\114\20\0"+
    "\4\6\4\0\1\6\1\0\11\6\3\0\2\6\1\115"+
    "\4\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\4\6\1\116\4\6\3\0\7\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\11\6\3\0\5\6\1\117\1\6\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\5\6\1\120"+
    "\3\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\1\6\1\121\7\6\3\0"+
    "\7\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\11\6\3\0\6\6\1\122\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\4\6"+
    "\1\123\4\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\11\6\3\0\4\6"+
    "\1\124\2\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\2\6\1\125\6\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\11\6\3\0\5\6\1\126\1\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\1\6"+
    "\1\127\7\6\3\0\7\6\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\5\6\1\130\3\6"+
    "\3\0\7\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\11\6\3\0\7\6\2\0\1\131"+
    "\2\6\4\0\1\6\24\0\1\132\34\0\4\6\4\0"+
    "\1\6\1\0\2\6\1\133\6\6\3\0\7\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\11\6\3\0\6\6\1\134\2\0\3\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\11\6\3\0\5\6"+
    "\1\135\1\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\4\6\1\136\4\6\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\3\6\1\137\5\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\11\6"+
    "\3\0\7\6\2\0\1\6\1\140\1\6\4\0\1\6"+
    "\5\0\4\6\4\0\1\6\1\0\5\6\1\141\3\6"+
    "\3\0\7\6\2\0\3\6\4\0\1\6\5\0\4\6"+
    "\4\0\1\6\1\0\11\6\3\0\7\6\2\0\1\142"+
    "\2\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\5\6\1\143\3\6\3\0\7\6\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\4\6\1\144"+
    "\4\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\2\6\1\145\6\6\3\0"+
    "\7\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\4\6\1\146\4\6\3\0\7\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\1\6\1\147\7\6\3\0\7\6\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\1\6\1\150"+
    "\7\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\1\6\1\151\7\6\3\0"+
    "\7\6\2\0\3\6\4\0\1\6\5\0\4\6\4\0"+
    "\1\6\1\0\11\6\3\0\3\6\1\152\3\6\2\0"+
    "\3\6\4\0\1\6\5\0\4\6\4\0\1\6\1\0"+
    "\4\6\1\153\4\6\3\0\7\6\2\0\3\6\4\0"+
    "\1\6\5\0\4\6\4\0\1\6\1\0\2\6\1\112"+
    "\6\6\3\0\7\6\2\0\3\6\4\0\1\6\5\0"+
    "\4\6\4\0\1\6\1\0\10\6\1\154\3\0\7\6"+
    "\2\0\3\6\4\0\1\6\5\0\4\6\4\0\1\6"+
    "\1\0\4\6\1\155\4\6\3\0\7\6\2\0\3\6"+
    "\4\0\1\6\5\0\4\6\4\0\1\6\1\0\10\6"+
    "\1\156\3\0\7\6\2\0\3\6\4\0\1\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3520];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\3\1\1\11"+
    "\7\1\1\11\5\1\2\11\2\1\3\11\1\1\1\11"+
    "\3\0\1\1\1\0\10\1\1\11\16\1\1\0\15\1"+
    "\1\0\15\1\1\11\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer cadena = new StringBuffer();
  int numErr = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2614) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { numErr++;return new Symbol(sym.error, yyline, yycolumn,yytext());
          }
        case 33: break;
        case 2: 
          { 
          }
        case 34: break;
        case 3: 
          { return new Symbol(sym.ID, yyline, yycolumn, yytext().toString());
          }
        case 35: break;
        case 4: 
          { return new Symbol(sym.LITERAL_ENTERA, yyline, yycolumn, yytext().toString());
          }
        case 36: break;
        case 5: 
          { return new Symbol(sym.OPERADOR_BINARIO, yyline, yycolumn, yytext().toString());
          }
        case 37: break;
        case 6: 
          { return new Symbol(sym.PAREN_DER, yyline, yycolumn);
          }
        case 38: break;
        case 7: 
          { return new Symbol(sym.OPERADOR_LOGICO, yyline, yycolumn, yytext().toString());
          }
        case 39: break;
        case 8: 
          { return new Symbol(sym.OPERADOR_COMPARACION, yyline, yycolumn, yytext().toString());
          }
        case 40: break;
        case 9: 
          { return new Symbol(sym.ASIGNACION, yyline, yycolumn);
          }
        case 41: break;
        case 10: 
          { return new Symbol(sym.LLAVE_IZQ, yyline, yycolumn);
          }
        case 42: break;
        case 11: 
          { return new Symbol(sym.LLAVE_DER, yyline, yycolumn);
          }
        case 43: break;
        case 12: 
          { return new Symbol(sym.MARCADOR_FIN_SENTENCIA, yyline, yycolumn);
          }
        case 44: break;
        case 13: 
          { cadena.setLength(0);yybegin(CADENA);
          }
        case 45: break;
        case 14: 
          { return new Symbol(sym.PAREN_IZQ, yyline, yycolumn);
          }
        case 46: break;
        case 15: 
          { cadena.append(yytext());
          }
        case 47: break;
        case 16: 
          { yybegin(YYINITIAL);return new Symbol(sym.LITERAL_CADENA, yyline, yycolumn,cadena.toString());
          }
        case 48: break;
        case 17: 
          { return new Symbol(sym.SI, yyline, yycolumn);
          }
        case 49: break;
        case 18: 
          { return new Symbol(sym.OPERADOR_UNARIO, yyline, yycolumn);
          }
        case 50: break;
        case 19: 
          { return new Symbol(sym.OP_LECTURA, yyline, yycolumn);
          }
        case 51: break;
        case 20: 
          { return new Symbol(sym.PARA, yyline, yycolumn);
          }
        case 52: break;
        case 21: 
          { return new Symbol(sym.LITERAL_NULA, yyline, yycolumn);
          }
        case 53: break;
        case 22: 
          { return new Symbol(sym.DESDE, yyline, yycolumn);
          }
        case 54: break;
        case 23: 
          { return new Symbol(sym.LITERAL_BOOLEANA, yyline, yycolumn, yytext().toString());
          }
        case 55: break;
        case 24: 
          { return new Symbol(sym.SI_NO, yyline, yycolumn);
          }
        case 56: break;
        case 25: 
          { return new Symbol(sym.HASTA, yyline, yycolumn);
          }
        case 57: break;
        case 26: 
          { return new Symbol(sym.ENTERO, yyline, yycolumn);
          }
        case 58: break;
        case 27: 
          { return new Symbol(sym.LOGICO, yyline, yycolumn);
          }
        case 59: break;
        case 28: 
          { return new Symbol(sym.CADENA, yyline, yycolumn);
          }
        case 60: break;
        case 29: 
          { return new Symbol(sym.OP_ESCRITURA, yyline, yycolumn);
          }
        case 61: break;
        case 30: 
          { return new Symbol(sym.ENTONCES, yyline, yycolumn);
          }
        case 62: break;
        case 31: 
          { return new Symbol(sym.PROGRAMA, yyline, yycolumn);
          }
        case 63: break;
        case 32: 
          { return new Symbol(sym.MIENTRAS, yyline, yycolumn);
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
