
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OP_ESCRITURA = 5;
  public static final int OP_LECTURA = 9;
  public static final int PROGRAMA = 2;
  public static final int CADENA = 25;
  public static final int HASTA = 20;
  public static final int ENTONCES = 23;
  public static final int LITERAL_BOOLEANA = 12;
  public static final int OPERADOR_UNARIO = 27;
  public static final int PARA = 18;
  public static final int ID = 8;
  public static final int PAREN_IZQ = 28;
  public static final int SI_NO = 22;
  public static final int OPERADOR_COMPARACION = 13;
  public static final int ASIGNACION = 16;
  public static final int PAREN_DER = 29;
  public static final int EOF = 0;
  public static final int MARCADOR_FIN_SENTENCIA = 6;
  public static final int SI = 21;
  public static final int error = 1;
  public static final int OPERADOR_BINARIO = 14;
  public static final int LITERAL_NULA = 26;
  public static final int OPERADOR_LOGICO = 15;
  public static final int LLAVE_IZQ = 3;
  public static final int DESDE = 19;
  public static final int ENTERO = 10;
  public static final int LLAVE_DER = 4;
  public static final int MIENTRAS = 17;
  public static final int LITERAL_CADENA = 7;
  public static final int LOGICO = 24;
  public static final int LITERAL_ENTERA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "OP_ESCRITURA",
  "MARCADOR_FIN_SENTENCIA",
  "LITERAL_CADENA",
  "ID",
  "OP_LECTURA",
  "ENTERO",
  "LITERAL_ENTERA",
  "LITERAL_BOOLEANA",
  "OPERADOR_COMPARACION",
  "OPERADOR_BINARIO",
  "OPERADOR_LOGICO",
  "ASIGNACION",
  "MIENTRAS",
  "PARA",
  "DESDE",
  "HASTA",
  "SI",
  "SI_NO",
  "ENTONCES",
  "LOGICO",
  "CADENA",
  "LITERAL_NULA",
  "OPERADOR_UNARIO",
  "PAREN_IZQ",
  "PAREN_DER"
  };
}

