
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAMA = 2;
  public static final int LLAVE_IZQ = 3;
  public static final int LLAVE_DER = 4;
  public static final int OP_ESCRITURA = 5;
  public static final int MARCADOR_FIN_SENTENCIA = 6;  
  public static final int LITERAL_CADENA = 7;  
  public static final int MIENTRAS = 8;  
  public static final int PARA = 9;  
  public static final int DESDE = 10;  
  public static final int HASTA = 11;  
  public static final int ENTONCES = 12;
  public static final int SI = 13;
  public static final int SI_NO = 14;
  public static final int ID = 15;
  public static final int NUMERO = 16;
  public static final int SIMBOLO = 17;
  public static final int OP_LECTURA = 18;
  public static final int ENTERO = 19;
  public static final int LOGICO = 20;
  public static final int LITERAL = 21;
  public static final int OPERADOR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "OP_ESCRITURA",
  "MARCADOR_FIN_SENTENCIA",
  "LITERAL_CADENA",
  "MIENTRAS",
  "PARA",
  "DESDE",
  "HASTA",
  "ENTONCES",
  "SI",
  "SI NO",
  "IDENTIFICADOR",
  "NUMERO",
  "SIMBOLO",
  "OP_LECTURA",
  "ENTERO",
  "LOGICO",
  "LITERAL",
  "OPERADOR"
  };
}

